-- =====================================================
-- Tutor Booking System - Database Schema (PostgreSQL)
-- BAI12153 Web Programming Project
--
-- NOTE: This project originally used MySQL/MariaDB (via XAMPP) for local
-- development, and was migrated to PostgreSQL so it could be deployed for
-- free on Render (which offers a genuinely free, no-credit-card managed
-- PostgreSQL instance, unlike the free MySQL options available).
-- =====================================================

-- Custom ENUM-like types. Postgres doesn't support inline ENUM('a','b')
-- inside CREATE TABLE like MySQL does, so we define reusable types instead.
CREATE TYPE user_role AS ENUM ('student', 'tutor');
CREATE TYPE booking_status AS ENUM ('pending', 'approved', 'rejected', 'cancelled');

-- ---------------------------------------------------
-- Table: users
-- Stores both students and tutors, differentiated by role
-- ---------------------------------------------------
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role user_role NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------
-- Table: tutor_profiles
-- Extra info only relevant to users with role = 'tutor'
-- One-to-one relationship with users
-- ---------------------------------------------------
CREATE TABLE tutor_profiles (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    subject VARCHAR(100) NOT NULL,
    bio TEXT,
    hourly_rate DECIMAL(6,2) DEFAULT 0.00
);

-- ---------------------------------------------------
-- Table: bookings
-- Core resource for CRUD. Links a student and a tutor.
-- One-to-many: one user (student) -> many bookings
-- One-to-many: one user (tutor)   -> many bookings
-- ---------------------------------------------------
CREATE TABLE bookings (
    id SERIAL PRIMARY KEY,
    student_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    tutor_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subject VARCHAR(100) NOT NULL,
    booking_date DATE NOT NULL,
    booking_time TIME NOT NULL,
    status booking_status DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------
-- Helpful indexes for search/filter performance
-- ---------------------------------------------------
CREATE INDEX idx_tutor_subject ON tutor_profiles(subject);
CREATE INDEX idx_booking_date ON bookings(booking_date);
CREATE INDEX idx_booking_status ON bookings(status);

-- ---------------------------------------------------
-- Sample seed data (optional, for quick testing)
-- Note: password_hash values below are placeholders.
-- Real hashed passwords will be generated by the app
-- via bcrypt during registration.
-- ---------------------------------------------------
-- INSERT INTO users (name, email, password_hash, role) VALUES
-- ('Alice Tan', 'alice@example.com', '$2b$10$placeholder', 'student'),
-- ('Mr. Lim', 'lim@example.com', '$2b$10$placeholder', 'tutor');
